version: 1
disable_existing_loggers: False
formatters:
  audit:
    format: '%(asctime)s - %(levelname)s - %(message)s'

handlers:
  audit_file:
    class: logging.handlers.RotatingFileHandler
    formatter: audit
    filename: logs/audit.log
    maxBytes: 10485760 # 10 MB
    backupCount: 7
    level: INFO

loggers:
  rpg_bot_audit:
    handlers: [audit_file]
    level: INFO
    propagate: False