version: 1
disable_existing_loggers: False
formatters:
  standard:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  audit:
    format: '%(asctime)s - %(levelname)s - %(message)s'

handlers:
  console:
    class: logging.StreamHandler
    formatter: standard
    level: INFO
  file:
    class: logging.handlers.RotatingFileHandler
    formatter: standard
    filename: logs/rpg_bot.log
    maxBytes: 10485760 # 10 MB
    backupCount: 5
    level: INFO
  audit_file:
    class: logging.handlers.RotatingFileHandler
    formatter: audit
    filename: logs/audit.log
    maxBytes: 10485760 # 10 MB
    backupCount: 7
    level: INFO

loggers:
  rpg_bot:
    handlers: [console, file]
    level: INFO
    propagate: False
  rpg_bot_audit:
    handlers: [audit_file]
    level: INFO
    propagate: False

root:
  handlers: [console]
  level: INFO